"""Stable public surface of the repository-generation capability."""

from repoctl.modules.repository_generation.adapters.outbound.local_repository import (
    LocalRepository,
)
from repoctl.modules.repository_generation.adapters.outbound.memory_repository import (
    MemoryRepository,
)
from repoctl.modules.repository_generation.application.ports import (
    RepositoryConflictError,
    RepositoryPathEscapeError,
    RepositoryPort,
    RepositoryPortError,
    RepositoryTransactionError,
    TransactionAlreadyExistsError,
    TransactionInspection,
    TransactionMissingError,
    TransactionState,
    TransactionStateError,
)
from repoctl.modules.repository_generation.domain.decisions import plan
from repoctl.modules.repository_generation.domain.indexes import (
    DerivedCapability,
    DerivedIndexes,
    canonical_index_bytes,
    compile_indexes,
)
from repoctl.modules.repository_generation.domain.intents import (
    CapabilityDeclaration,
    CapabilityIntent,
    CapabilityStatus,
    RepositoryFile,
    RepositoryPath,
    RepositorySnapshot,
)
from repoctl.modules.repository_generation.domain.ownership import (
    AbsolutePathError,
    AmbiguousOwnershipError,
    DotPathSegmentError,
    EmptyPathSegmentError,
    NonCanonicalSeparatorError,
    OwnershipPathError,
    OwnershipRoot,
    OwnershipZone,
    OwnershipZoneRoots,
    ParentPathError,
    RepositoryPathCandidate,
    UnclassifiedPathError,
    UnicodeNormalizationPathError,
    classify_path,
    matching_zones,
    validated_segments,
)
from repoctl.modules.repository_generation.domain.plans import (
    CapabilityPlan,
    Operation,
    canonical_plan_bytes,
    content_digest,
    make_plan,
)
from repoctl.modules.repository_generation.domain.plans_planner import (
    PlanningOwnershipError,
    intended_target_paths,
)
from repoctl.modules.repository_generation.domain.specifications import (
    DeclarationIndexFacts,
    DerivedIndexFacts,
    OwnershipRootFacts,
    classified_path_is_closed,
    derived_indexes_are_exact,
    plan_repetition_is_identical,
)

__all__ = [
    "AbsolutePathError",
    "AmbiguousOwnershipError",
    "CapabilityDeclaration",
    "CapabilityIntent",
    "CapabilityPlan",
    "CapabilityStatus",
    "DeclarationIndexFacts",
    "DerivedCapability",
    "DerivedIndexFacts",
    "DerivedIndexes",
    "DotPathSegmentError",
    "EmptyPathSegmentError",
    "LocalRepository",
    "MemoryRepository",
    "NonCanonicalSeparatorError",
    "Operation",
    "OwnershipPathError",
    "OwnershipRoot",
    "OwnershipRootFacts",
    "OwnershipZone",
    "OwnershipZoneRoots",
    "ParentPathError",
    "PlanningOwnershipError",
    "RepositoryConflictError",
    "RepositoryFile",
    "RepositoryPath",
    "RepositoryPathCandidate",
    "RepositoryPathEscapeError",
    "RepositoryPort",
    "RepositoryPortError",
    "RepositorySnapshot",
    "RepositoryTransactionError",
    "TransactionAlreadyExistsError",
    "TransactionInspection",
    "TransactionMissingError",
    "TransactionState",
    "TransactionStateError",
    "UnclassifiedPathError",
    "UnicodeNormalizationPathError",
    "canonical_index_bytes",
    "canonical_plan_bytes",
    "classified_path_is_closed",
    "classify_path",
    "compile_indexes",
    "content_digest",
    "derived_indexes_are_exact",
    "intended_target_paths",
    "make_plan",
    "matching_zones",
    "plan",
    "plan_repetition_is_identical",
    "validated_segments",
]
